steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'bundle']
    env: ['NODE_ENV=production']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['publish']
    secretEnv: ['NPM_TOKEN']

secrets:
- kmsKeyName: projects/rfh-prod/locations/global/keyRings/ci/cryptoKeys/NPM_TOKEN
  secretEnv:
    NPM_TOKEN: CiQAdaIEJ31IxPcFfOQklXlVvyEBa+hRtFFJ8ynfqlTX+4imQlASUQCBAGErS3SRBfY+OgwPu2fTR/TqTkCftmh9qhOcWYZozRbs/k3HArzQpDaHYrMaIEi7wyjnF0Er4W7libuub9e7eN+1l5OIbjyIZbevxZYvRw==
