steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['i', '-D']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'bundle']
    env: ['NODE_ENV=production']
    secretEnv: ['NPM_TOKEN']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['publish']
